""" C++ specific build nodes. """

import json
import subprocess

from node.node import Node


class NodeCpp(Node):
    """ C++ source file build node. """

    def __init__(self, env, src):
        super(NodeCpp, self).__init__(env=env, src=src)
        base = src.rsplit('.', 1)[0]

        self._obj = env.build_dir / f'{base}.o'
        self._jsn = env.build_dir / f'{base}.json'
        self._gcm = env.cache_dir / f'{base}.gcm'
        self.dep_modules = []

    def pre_scan(self):
        super(NodeCpp, self).pre_scan()
        # Regardless of all else, if the object isn't built then the node is dirty.
        if not self._obj.exists():
            self.dirty = True

    def clean(self):
        if self._obj.exists():
            self._obj.unlink()
        if self._jsn.exists():
            self._jsn.unlink()
        if self._gcm.exists():
            self._gcm.unlink()

    def obj(self):
        return str(self._obj)

    def jsn(self):
        return str(self._jsn)

    def gcm(self):
        return str(self._gcm)

    def build_json(self):
        """ Build or rebuild a json file describing source dependencies.
        Build if not already exist, or rebuild if the source file has changed, a json
        description of the file and any module dependencies it has.

        :returns: True if there was a build action, else False
        """
        if not self.dirty and self._jsn.exists():
            # The file hasn't changed and the appropriate json exists, don't bother with more.
            return False

        # Make sure the subdirectoy for the build output exists.
        dirpath = self._jsn.parent
        if not dirpath.exists():
            dirpath.mkdir(parents=True)

        # Generate a builder command.
        builder = [
            '-M',
            '-MF', '/dev/null',
            '-fdeps-format=p1689r5',
            f'-fdeps-file={self._jsn}',
            f'-fdeps-target={self._obj.relative_to(self.env.build_dir)}',
            self.src()
        ]
        full = self.env.compile_commands + builder
        print(' '.join(full))
        subprocess.run(full, encoding='utf-8')
        return True

    def build_map(self):
        with open(self.jsn(), 'r') as jfile:
            dep = json.load(jfile)
            for rule in dep.get('rules', []):
                for prov in rule.get('provides', []):
                    if prov.get('is-interface', False):
                        logical = prov['logical-name']
                        self.env.mapper[logical] = self
                for req in rule.get('requires', []):
                    self.dep_modules.append(req['logical-name'])

    def build_deps(self):
        for dep in self.dep_modules:
            if dep in self.env.mapper:
                self.dep_nodes.append(self.env.mapper[dep])

    def _build_obj(self):
        """ Perform a build of this object assuming all dependencies are satisfied.
        """
        if self.dirty or not self._obj.exists():
            # Make sure the target path to the object exists.
            dirpath = self._obj.parent
            if not dirpath.exists():
                dirpath.mkdir(parents=True)

            builder = [
                f'-fmodule-mapper={self.env.mapfile}',
                '-o', self.obj(),
                '-c', self.src()
            ]
            full = self.env.compile_commands + builder
            print(' '.join(full))
            subprocess.run(full, encoding='utf-8')
            self.dirty = False

    def build_obj(self):
        """ Build or rebuild an object file.
        Build if not already exist, or rebuild if the source file has changed, an object
        file and any dependencies it has
        """

        # First make sure any dependencies are built.
        for dep in self.dep_nodes:
            if dep.dirty:
                # If a dependency is dirty, then this node will need rebuilding too.
                self.dirty = True
                dep.build_obj()

        self._build_obj()

    def build_obj_submit(self, executor):
        """ Traverse dependencies and submit build task if possible.
        Iterates over the existing dependencies; if all dependencies are clean
        then submit a build task for (this) node.
        """
        dirty_nodes = [dep for dep in self.dep_nodes if dep.dirty]
        if len(dirty_nodes) == 0:
            executor.submit(self._build_obj)
        else:
            self.dirty = True
            for dep in dirty_nodes:
                dep.build_obj_submit(executor)



build_id_template = """
/**
 * This file is automatically generated. Do not edit.
 */

static const char GIT_COMMIT[] __attribute__((used)) = "%s";

const char *getGitCommit() {
    return GIT_COMMIT;
}

"""


class NodeVersion(NodeCpp):
    """ Creates a version.cpp node for git build information.
    Automatically generates version.cpp based on git information whenever the build is
    executed. Although generated every time, if the md5 does not change then a rebuild
    of the executable is not required.
    """

    def __init__(self, env, src='version.cpp'):
        self.version_src = env.build_dir / src
        super(NodeVersion, self).__init__(env=env, src=src)

    def src(self):
        """ Override src directory to point to the build directory. """
        return str(self.version_src)

    def pre_scan(self):
        """ Generate the version source file as necessary. """
        githash = subprocess.check_output(["git", "rev-parse", "HEAD"]).strip().decode()
        gcc_version = subprocess.check_output(['g++', '--version']).strip().decode()
        print(gcc_version)
        generated = build_id_template % (githash)
        with open(self.version_src, 'w') as fd:
            fd.write(generated)
        super(NodeVersion, self).pre_scan()


    def clean(self):
        """ Delete all generated files, including version.cpp if it exists. """
        super(NodeVersion, self).clean()
        if self.version_src.exists():
            self.version_src.unlink()
